### PR TITLE
Add json output formatter

### PR DESCRIPTION
**Pull request by shakhat**
The patch extends output parameter with option "json". With it netperf-wrapper prints raw json data to stdout.

### CODE REVIEW

**Comment by tohojo** [comment]
What's the use case? The data files are already json...

**Comment by shakhat** [comment]
Use case is following: My tool runs netperf-wrapper on remote machine as a single command (e.g. "ssh <host> netperf-wrapper <params>"). The tool captures stdout and then calculates stats on the local machine. 
Currently netperf-wrapper writes json into a separate file which makes it harder to unitilize it as one command (the possible workaround is to run netperf-wrapper without formatter, grep out file name and then cat this name onto stdout)

**Comment by tohojo** [comment]
Right, that makes sense. I'd prefer it if there wasn't a difference in
the output generated by this and the results file, though. Storing the
units in the metadata is probably a good idea in any case, so that
should be added to the resultset somewhere. Will think about where it
makes the most sense.

Also, to make this be compatible with the results format, the outermost
json object shouldn't be wrapped in a list if there's only one
resultset. And detecting a .gz extension and applying gzip compression
would be nice.

Feel free to resubmit a pull request with the above changes. Otherwise,
I'll put it on my list. If you do resubmit, please add a Signed-Off-By:
header to the commit message.

Thanks,
-Toke

**Comment by shakhat** [comment]
Ok, I'll update the patch accordingly. It would be even better to split it into two: one for units in json data file and other for json formatter.

Regards,
-Ilya

**Comment by tohojo** [comment]
> Ok, I'll update the patch accordingly. It would be even better to split it into
> two: one for units in json data file and other for json formatter.

Great! You're right that splitting them up makes sense; but feel free to
do them as two commits in one pull request if that is less of a hassle :)

The 'units in the results' part should probably go in
Aggregator.collect() somewhere...

-Toke

**Comment by tohojo** [comment]
Closing for now. Please open a new pull request if you re-do the patch :)

**Pull request closed without merging**
